version: "3.8"
services:
  cache:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
  api:
    build: ./lowLevelCache
    command: bundle exec puma -C config/puma.rb
    restart: always
    volumes:
      - ./lowLevelCache:/app
    ports:
      - "3000:3000"
    depends_on:
      - cache
